version: 1
project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/ignis.lpk
  target_arch: amd64
update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: ignis
build:
  toolchains: []
  run_buildscript: false
images:
  - id: ignis
    target: service
    service: ignis
    source: nobbe/ignis
    channel: stable
    sort: semver
    tag_regex: '^\d+\.\d+\.\d+$'
    delivery:
      mode: mirror
      require_digest_match: true
stores:
  official:
    enabled: false
  private:
    enabled: true
    skip_if_version_exists: true
    name: Ignis
    summary: Run Obsidian as a self-hosted web app. Not remote desktop, an actual web app.
